### PR TITLE
Switched to a variable-input port approach for the vt_xmltonc wrapper

### PR DESCRIPTION
**Pull request by captainceramic**
@DamienIrving - I've had a go a re-writing this so that you can provide different numbers of inputs. I have tested the time starts and ends, but not the lat/lon cropping.

All cropping variables are optional, except for the start and end times. This is because the Nino34 workflow requires input and output times. This could be re-written to avoid this problem.

### CODE REVIEW

**Comment by DamienIrving** [comment]
Can we make the times optional too? I can then update the Nino34 workflow if you like?

**Comment by captainceramic** [comment]
Sure - I'll do that now.

**Comment by captainceramic** [comment]
I think this should do it - I think the final thing we should do with this one is either switch the types of the input ports for lat/lon bounds etc. to Strings, or change them all to floating-point and convert them into strings when `getInputFromPort` gets called.

**Comment by captainceramic** [comment]
I think this is ready to go now. Check it out when you have a chance.

**Pull request merged**
